import { Project } from "@/types";

export const PROJECTS: Project[] = [
  {
    id: "silk-road",
    name: "Silk Road Residences",
    developer: {
      name: "UzInvest Group",
      verified: true,
      logo: "https://picsum.photos/seed/uzinvest/100/100",
    },
    location: "Tashkent",
    district: "Mirabad District",
    priceFrom: 240000,
    deliveryDate: "Q2 2025",
    floors: 18,
    isPopular: true,
    image: "https://picsum.photos/seed/silk/1200/800",
    description:
      "Experience luxury living at the heart of the Silk Road. Modern design meets traditional aesthetics.",
    tags: ["Luxury", "Modern", "Central Location"],
    images: [
      "https://picsum.photos/seed/silk/1200/800",
      "https://picsum.photos/seed/silk-2/1200/800",
    ],
    mainImage: "https://picsum.photos/seed/silk/1200/800",
    apartments: [
      {
        id: "s1",
        projectId: "silk-road",
        rooms: 0,
        area: 42.5,
        floor: 12,
        price: 51000,
        status: "available",
        layoutImage: "https://picsum.photos/seed/silk-layout-1/600/400",
      },
      {
        id: "s2",
        projectId: "silk-road",
        rooms: 2,
        area: 78.2,
        floor: 8,
        price: 93840,
        status: "available",
        layoutImage: "https://picsum.photos/seed/silk-layout-2/600/400",
      },
    ],
  },
  {
    id: "infinity",
    name: "Infinity Residences",
    developer: {
      name: "Golden House",
      verified: true,
      logo: "https://picsum.photos/seed/golden/100/100",
    },
    location: "Tashkent",
    district: "Yunusabad District",
    priceFrom: 180000,
    deliveryDate: "Q4 2025",
    floors: 24,
    isPopular: true,
    image: "https://picsum.photos/seed/infinity/1200/800",
    description:
      "Limitless comfort and breathtaking views in the most dynamic district of Tashkent.",
    tags: ["Modern", "High-rise", "Amenities"],
    images: [
      "https://picsum.photos/seed/infinity/1200/800",
      "https://picsum.photos/seed/infinity-2/1200/800",
    ],
    mainImage: "https://picsum.photos/seed/infinity/1200/800",
    apartments: [
      {
        id: "i1",
        projectId: "infinity",
        rooms: 1,
        area: 55.0,
        floor: 15,
        price: 65000,
        status: "available",
        layoutImage: "https://picsum.photos/seed/infinity-layout-1/600/400",
      },
    ],
  },
  {
    id: "gardenia",
    name: "Gardenia Heights",
    developer: {
      name: "GreenBuild Co.",
      verified: true,
      logo: "https://picsum.photos/seed/greenbuild/100/100",
    },
    location: "Tashkent",
    district: "Mirzo-Ulugbek District",
    priceFrom: 120000,
    deliveryDate: "Q1 2026",
    floors: 12,
    image: "https://picsum.photos/seed/garden/1200/800",
    description:
      "A green oasis in the urban landscape. Ecological materials and smart design.",
    tags: ["Green Building", "Eco-friendly", "Spacious"],
    images: [
      "https://picsum.photos/seed/garden/1200/800",
      "https://picsum.photos/seed/garden-2/1200/800",
    ],
    mainImage: "https://picsum.photos/seed/garden/1200/800",
    apartments: [],
  },
  {
    id: "sky-tower",
    name: "Sky Tower Loft",
    developer: {
      name: "Skyline Developers",
      verified: false,
      logo: "https://picsum.photos/seed/skyline/100/100",
    },
    location: "Tashkent",
    district: "Shaykhantakhur District",
    priceFrom: 155000,
    deliveryDate: "Ready",
    floors: 45,
    isPopular: false,
    image: "https://picsum.photos/seed/sky/1200/800",
    description:
      "Reach for the stars. The tallest residential building in Central Asia.",
    tags: ["Tallest Building", "Luxury Lofts", "Downtown"],
    images: [
      "https://picsum.photos/seed/sky/1200/800",
      "https://picsum.photos/seed/sky-2/1200/800",
    ],
    mainImage: "https://picsum.photos/seed/sky/1200/800",
    apartments: [],
  },
];
