import { Project } from '../types';

export const projects: Project[] = [
  {
    id: '1',
    name: 'Infinity Residence',
    description: 'Modern luxury living in the heart of Tashkent. Features panoramic views and premium amenities.',
    location: 'Tashkent',
    developer: {
      name: 'Golden House',
      verified: true,
      logo: 'https://picsum.photos/seed/gh/100/100',
    },
    deliveryDate: 'Q4 2025',
    tags: ['Luxury', 'City Center', 'Concierge'],
    mainImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=1000',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1000',
    ],
    priceFrom: 120000,
    apartments: [
      {
        id: 'a1',
        projectId: '1',
        rooms: 2,
        area: 65,
        floor: 5,
        price: 125000,
        status: 'available',
        layoutImage: 'https://picsum.photos/seed/plan1/400/400',
      },
      {
        id: 'a2',
        projectId: '1',
        rooms: 3,
        area: 92,
        floor: 12,
        price: 185000,
        status: 'available',
        layoutImage: 'https://picsum.photos/seed/plan2/400/400',
      },
    ],
  },
  {
    id: '2',
    name: 'Silk Road Plaza',
    description: 'Authentic Samarkand architecture meets modern comfort. Historical neighborhood with modern infrastructure.',
    location: 'Samarkand',
    developer: {
      name: 'Samarkand Dev',
      verified: true,
      logo: 'https://picsum.photos/seed/sd/100/100',
    },
    deliveryDate: 'Q2 2026',
    tags: ['Historical', 'Family Friendly', 'Plaza'],
    mainImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1000',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1000',
    ],
    priceFrom: 85000,
    apartments: [
      {
        id: 'a3',
        projectId: '2',
        rooms: 1,
        area: 45,
        floor: 2,
        price: 85000,
        status: 'available',
        layoutImage: 'https://picsum.photos/seed/plan3/400/400',
      },
    ],
  },
  {
    id: '3',
    name: 'Bukhara Old Town',
    description: 'Exclusive boutique apartments with traditional design elements and courtyard views.',
    location: 'Bukhara',
    developer: {
      name: 'Heritage Build',
      verified: false,
      logo: 'https://picsum.photos/seed/hb/100/100',
    },
    deliveryDate: 'Q1 2027',
    tags: ['Boutique', 'Tradition', 'Courtyard'],
    mainImage: 'https://images.unsplash.com/photo-1448630360428-65ff24c95de7?auto=format&fit=crop&q=80&w=1000',
    images: [
      'https://images.unsplash.com/photo-1448630360428-65ff24c95de7?auto=format&fit=crop&q=80&w=1000',
    ],
    priceFrom: 95000,
    apartments: [
      {
        id: 'a4',
        projectId: '3',
        rooms: 2,
        area: 58,
        floor: 3,
        price: 98000,
        status: 'available',
        layoutImage: 'https://picsum.photos/seed/plan4/400/400',
      },
    ],
  },
];
